steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', '-t', 'gcr.io/neutralnews-ca548/cleanup-old-news-image', '.']
  # Add cacheFrom to potentially speed up builds by reusing layers from previous builds
  # Note: This requires the previous image to exist in the registry.
  args: ['build', '--cache-from', 'gcr.io/neutralnews-ca548/cleanup-old-news-image', '-t', 'gcr.io/neutralnews-ca548/cleanup-old-news-image', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/neutralnews-ca548/cleanup-old-news-image']

# Define the image to be pushed after the build is complete
images:
- 'gcr.io/neutralnews-ca548/cleanup-old-news-image'